-- RLS policies for SpecBoard multi-tenant isolation.
--
-- Run AFTER the table DDL generated by `pnpm --filter @specboard/db generate`
-- (drizzle-kit emits table migrations into this directory). This file enables
-- row-level security and scopes every tenant table by workspace membership.
--
-- The pattern: a row is visible/editable only if the current auth user is a
-- member of that row's workspace. `auth.uid()` is provided by Supabase Auth.

create or replace function specboard_is_member(target_workspace uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from members m
    where m.workspace_id = target_workspace
      and m.user_id = auth.uid()
  );
$$;

-- Enable RLS + membership policy on each tenant-scoped table.
do $$
declare
  t text;
begin
  foreach t in array array[
    'workspaces', 'members', 'repositories', 'features', 'comments', 'activity_log'
  ]
  loop
    execute format('alter table %I enable row level security;', t);
  end loop;
end $$;

-- workspaces: members can see their own workspace row.
create policy workspaces_member_select on workspaces
  for select using (specboard_is_member(id));

-- Tenant tables that carry workspace_id directly.
create policy features_member_all on features
  for all using (specboard_is_member(workspace_id))
  with check (specboard_is_member(workspace_id));

create policy repositories_member_all on repositories
  for all using (specboard_is_member(workspace_id))
  with check (specboard_is_member(workspace_id));

create policy comments_member_all on comments
  for all using (specboard_is_member(workspace_id))
  with check (specboard_is_member(workspace_id));

create policy activity_member_all on activity_log
  for all using (specboard_is_member(workspace_id))
  with check (specboard_is_member(workspace_id));

create policy members_member_select on members
  for select using (specboard_is_member(workspace_id));

-- spec_index has no workspace_id column; join through its feature.
alter table spec_index enable row level security;
create policy spec_index_member_all on spec_index
  for all using (
    exists (
      select 1 from features f
      where f.id = spec_index.feature_id
        and specboard_is_member(f.workspace_id)
    )
  );
